INSERT INTO stockmanufacturer (id, name) VALUES (1, 'Abbot');
INSERT INTO stockmanufacturer (id, name) VALUES (2, 'Adcock Ingram');
INSERT INTO stockmanufacturer (id, name) VALUES (3, 'Aspen');
INSERT INTO stockmanufacturer (id, name) VALUES (4, 'Aurobindo');
INSERT INTO stockmanufacturer (id, name) VALUES (5, 'Cipla');
INSERT INTO stockmanufacturer (id, name) VALUES (6, 'GlaxoSmithKline');
INSERT INTO stockmanufacturer (id, name) VALUES (7, 'Mylan');
INSERT INTO stockmanufacturer (id, name) VALUES (8, 'Pfizer');
INSERT INTO stockmanufacturer (id, name) VALUES (9, 'Pharma Dynamics');
INSERT INTO stockmanufacturer (id, name) VALUES (10, 'Sandoz');
INSERT INTO stockmanufacturer (id, name) VALUES (11, 'Sanofi Aventis');
INSERT INTO stockmanufacturer (id, name) VALUES (12, 'Winthrop');
INSERT INTO stockmanufacturer (id, name) VALUES (13, 'DPR');
INSERT INTO stockmanufacturer (id, name) VALUES (14, 'Medpro');
INSERT INTO stockmanufacturer (id, name) VALUES (15, 'Medivision');
INSERT INTO stockmanufacturer (id, name) VALUES (16, 'Specpharm');
INSERT INTO stockmanufacturer (id, name) VALUES (17, 'Pharmacare');
INSERT INTO stockmanufacturer (id, name) VALUES (18, 'MSD');
INSERT INTO stockmanufacturer (id, name) VALUES (19, 'Dezzo');
INSERT INTO stockmanufacturer (id, name) VALUES (20, 'Sonke');
INSERT INTO stockmanufacturer (id, name) VALUES (21, 'Abbot');